spring:
  datasource:
    uesrname: root
    password: 1122
    url: jdbc:mysql://localhost:3306/forball?useUnicde=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
config:
  c3p0:
      # 连接池中保留的最大连接数
          max_size: 10
          # 连接池中保留的最小连接数
          min_size: 3
          # 初始化连接数
          init_size: 3
          # 当连接池中的连接用完时，C3P0一次性创建新连接的数目
          acquire_increment: 2
          idle_test_period: 3600
          max_statements: 3
          max_idle_time: 3600
          url: jdbc:mysql://localhost:3306/forball?useUnicode=true&characterEncoding=UTF-8
          username: root
          password: 123456
          driverClassName: com.mysql.jdbc.Driver